import { writeFile, mkdir } from "node:fs/promises";
import { dirname, join } from "node:path";

export async function writeDashboard(
  stateFile: string,
  statusText: string
): Promise<void> {
  try {
    const baseDir = dirname(stateFile);
    await mkdir(baseDir, { recursive: true });

    const content = [
      "<!-- Auto-generated by project_status. Do not edit manually. -->",
      `<!-- Updated: ${new Date().toISOString()} -->`,
      "",
      statusText,
      "",
    ].join("\n");

    await writeFile(join(baseDir, "dashboard.md"), content, "utf-8");
  } catch {
    // dashboard write should never break the main flow
  }
}
