import { describe, it, expect, afterEach } from "vitest";
import { readFile, rm } from "node:fs/promises";
import { join, dirname } from "node:path";
import { writeDashboard } from "../tools/dashboard.js";

const TEST_DIR = "/tmp/scrum-test-dashboard";
const STATE_FILE = `${TEST_DIR}/state.json`;

afterEach(async () => {
  try { await rm(TEST_DIR, { recursive: true }); } catch { /* ignore */ }
});

describe("writeDashboard", () => {
  it("dashboard.md を生成する", async () => {
    await writeDashboard(STATE_FILE, "# Status\nAll good");

    const content = await readFile(join(dirname(STATE_FILE), "dashboard.md"), "utf-8");
    expect(content).toContain("Auto-generated by project_status");
    expect(content).toContain("# Status");
    expect(content).toContain("All good");
  });

  it("更新日時のコメントを含む", async () => {
    await writeDashboard(STATE_FILE, "Test");

    const content = await readFile(join(dirname(STATE_FILE), "dashboard.md"), "utf-8");
    expect(content).toContain("Updated:");
  });

  it("上書き更新される", async () => {
    await writeDashboard(STATE_FILE, "First");
    await writeDashboard(STATE_FILE, "Second");

    const content = await readFile(join(dirname(STATE_FILE), "dashboard.md"), "utf-8");
    expect(content).not.toContain("First");
    expect(content).toContain("Second");
  });
});
